include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test_firebase_project/**
  errors:
    use_build_context_synchronously: ignore
    avoid_print: ignore
    file_names: ignore
    library_private_types_in_public_api: ignore
    deprecated_member_use: ignore
    unused_field: ignore

linter:
  rules:
    