name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase Dependencies
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.2.7
  firebase_messaging: ^14.7.0
  provider: ^6.0.5 
  shared_preferences: ^2.0.15

  # ✅ Authentication & Social Login
  google_sign_in: ^6.1.6

  # ✅ Logging & Utilities
  logger: ^2.0.2+1
  intl: ^0.18.1
  uuid: ^4.1.0
  http: ^1.2.0

  # ✅ Media & Image Handling
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0

  # ✅ Charts & Graphs
  fl_chart: ^0.68.0

  # ✅ UI & Animations
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.2.0

  # ✅ للإشعارات المحلية
  animations: ^2.0.11                    # ✅ لتحسين الأنيميشن في Bottom Sheets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
firebase_analytics: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg

